export const Paths = {
  SSO: {
    login: "/sso/login",
    loginByOtp: "/sso/login-by-otp",
    oneTimePassword: "/sso/otp",
    register: "/sso/register",
    forgetPassword: "/sso/forget-password",
    resetPassword: "/sso/reset-password",
    welcome: "/sso/welcome",
    SelectRole: "/sso/select-role",
  },
  HRLink: {
    Dashboard: "/hrlink/dashboard",
    ResumeInformation: "/hrlink/resume/information",
    ResumeExperience: "/hrlink/resume/experience",
    ResumeEducation: "/hrlink/resume/education",
    ResumeCourse: "/hrlink/resume/course",
    ResumeAwards: "/hrlink/resume/awards",
    ResumeHardSkills: "/hrlink/resume/hard-skills",
    ResumeSoftSkills: "/hrlink/resume/soft-skills",
    JobOffers: "/hrlink/job/offers",
    JobOpportunities: "/hrlink/job/opportunities",
    JobDetail: "/hrlink/job/show/:id",
    Setting: "/hrlink/setting",
    AllCompanies: "/hrlink/company/all-companies",
    CompanyJobOffers: "/hrlink/company/job-offers",
    CompanyEvents: "/hrlink/company/events",
    CompanyFavorites: "/hrlink/company/favorites",
    CompanyRequested: "/hrlink/company/requested",
    CompanyInformation: "/hrlink/company/company-information",
  },
  ChartMaker: {
    Dashboard: "/chart-maker/dashboard",
    ProcessMaker: "/chart-maker/process",
    ProcessList: "/chart-maker/process-list",
  },
  ProjectManagement: {
    Dashboard: "/project-management/dashboard",
  },
  BasicInfo: {
    Dashboard: "/basic-info/dashboard",
    TechnicalDepartment: "/basic-info/technical-departments",
    OrganizationDepartments: "/basic-info/organization-departments",
    OrganizationalLocations: "/basic-info/organizational-locations",
    AllEmployees: "/basic-info/all-employees",
    SatisfactionStatus: "/basic-info/satisfaction-status",
    PersonalInformation: "/basic-info/personal-information",
    Documents: "/basic-info/documents",
    Jobs: "/basic-info/jobs",
    Educations: "/basic-info/educations",
    Skills: "/basic-info/skills",
    Courses: "/basic-info/courses",
    Achievements: "/basic-info/achievement",
    Dependents: "/basic-info/dependents",
    OrganizationSpecificInformation:
      "/basic-info/organization-specific-information",
    Onboarding: "/basic-info/onboarding",
    Offboarding: "/basic-info/offboarding",
    Guidelines: "/basic-info/guidelines",
    TestReport: "/basic-info/test-report",
    ContractList: "/basic-info/contract-list",
    RequestList: "/basic-info/request-list",
    HealthRecords: "/basic-info/health-records",
    EmployeeSatisfactionCalendar: "/basic-info/employee-satisfaction-calendar",
  },
  Attendance: {
    Dashboard: "/attendance/dashboard",
    EntryExitRegistration: "/attendance/entry-exit",
    AttendanceCalenders: "/attendance/attendance-calender",
    TrafficCalender: "/attendance/traffic-calender",
    ListOfApprovals: "/attendance/list-of-approvals",
    Export: "/attendance/export",
    ShiftAllocation: "/attendance/shift-allocation",
    FaceAllocation: "/attendance/face-allocation",
    IpAllocation: "/attendance/ip-allocation",
    LocationAllocation: "/attendance/location-allocation",
  },
  ProcessMaker: {
    Dashboard: "/process-maker/dashboard",
    ProcessList: "/process-maker/process-list",
    ProcessExperience: "/process-maker/process-experience",
  },
};
