import SelectRole from "sso/pages/SelectRole";

export const Paths = {
  SSO:{
    login: '/login',
    loginByOtp: '/login-by-otp',
    oneTimePassword: '/otp',
    register: '/register',
    forgetPassword: '/forget-password',
    resetPassword: '/reset-password',
    welcome: '/welcome',
    SelectRole: '/sso/select-role',
  },
  HRLink:{
    Dashboard: '/dashboard',
    ResumeInformation: '/resume/information',
    ResumeExperience: '/resume/experience',
    ResumeEducation: '/resume/education',
    ResumeCourse: '/resume/course',
    ResumeAwards: '/resume/awards',
    ResumeHardSkills: '/resume/hard-skills',
    ResumeSoftSkills: '/resume/soft-skills',
    JobOffers: '/job/offers',
    JobOpportunities: '/job/opportunities',
    JobDetail: '/job/show/:id',
    Setting: '/setting',
    AllCompanies: '/company/all-companies',
    CompanyJobOffers: '/company/job-offers',
    CompanyEvents: '/company/events',
    CompanyFavorites: '/company/favorites',
    CompanyRequested: '/company/requested',
    CompanyInformation: '/company/company-information',
  },
  ChartMaker:{
    Dashboard: '/dashboard',
    ProcessMaker: '/process',
    ProcessList: '/process-list',
  },
  Attendance:{
    Dashboard: '/attendance/dashboard',
    EntryExitRegistration: '/attendance/entry-exit',
    AttendanceCalenders: '/attendance/attendance-calender',
    TrafficCalender: '/attendance/traffic-calender',
    ListOfApprovals: '/attendance/list-of-approvals',
    Export: '/attendance/export',
    ShiftAllocation: '/attendance/shift-allocation',
    FaceAllocation: '/attendance/face-allocation',
    IpAllocation: '/attendance/ip-allocation',
    LocationAllocation: '/attendance/location-allocation',
  }
};
