export const Paths = {
  SSO:{
    login: '/login',
    loginByOtp: '/login-by-otp',
    oneTimePassword: '/otp',
    register: '/register',
    forgetPassword: '/forget-password',
    resetPassword: '/reset-password',
    welcome: '/welcome',
  },
  HRLink:{
    Impersonate: '/impersonate',
    Dashboard: '/dashboard',
    ResumeInformation: '/resume/information',
    ResumeExperience: '/resume/experience',
    ResumeEducation: '/resume/education',
    ResumeCourse: '/resume/course',
    ResumeAwards: '/resume/awards',
    ResumeHardSkills: '/resume/hard-skills',
    ResumeSoftSkills: '/resume/soft-skills',
    JobOffers: '/job/offers',
    JobOpportunities: '/job/opportunities',
    JobDetail: '/job/show/:id',
    Setting: '/setting',
    AllCompanies: '/company/all-companies',
    CompanyJobOffers: '/company/job-offers',
    CompanyEvents: '/company/events',
    CompanyFavorites: '/company/favorites',
    CompanyRequested: '/company/requested',
    CompanyInformation: '/company/company-information',
  },
  ChartMaker:{
    Dashboard: '/dashboard',
    ProcessMaker: '/process',
    ProcessList: '/process-list',
  },
  Attendance:{
    Dashboard: '/dashboard',
    EntryExitRegistration: '/entry-exit',
    AttendanceCalenders: '/attendance-calender',
    TrafficCalender: '/traffic-calender',
    ListOfApprovals: '/list-of-approvals',
    Export: '/export',
    ShiftAllocation: '/shift-allocation',
    FaceAllocation: '/face-allocation',
    IpAllocation: '/ip-allocation',
    LocationAllocation: '/location-allocation',
  }
};
