packages:
  - core
  - core/*
  - modules
  - modules/*
  - UIKit
  - UIKit/*
  - launcher
  - proxy-server

ignoredBuiltDependencies:
  - '@swc/core'

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - cwebp-bin
  - esbuild
  - gifsicle
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - sharp
  - unrs-resolver
