packages:
  - core/*
  - modules/*
  - launcher

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - cwebp-bin
  - esbuild
  - gifsicle
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - sharp
  - unrs-resolver
