import { color, number } from "framer-motion";
import {
  CloseCircle,
  Global,
  Location,
  TickCircle,
  Verify,
} from "iconsax-reactjs";

export const EntryExitData = [
  {
    Id: 1,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 2,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Location /> <span>Location</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 3,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 4,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Location /> <span>Location</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 5,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
];
export const PersonalList = [
  {
    Date: "2025/01/01 Wednesday (Absence)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    isHoliday: false,
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    isHoliday: true,
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Absence)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: false,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: false,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: true,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
];
export const ReportPersonnal = [
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
];
export const ListApprovals = [
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: <TickCircle color="green" variant="Bold" />,
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
];
export const organization = [
  { id: "1", title: "Number of jobs graded", number: "28" },
  { id: "2", title: "Number of employees with grades", number: "53" },
  { id: "3", title: "Ungraded jobs", number: "12" },
  { id: "4", title: "Unemployed jobs", number: "3" },
];
export const JD_DATA = [
  {
    id: "1",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "2",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "3",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "4",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "5",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "6",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "7",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "8",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "9",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "10",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "11",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "12",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "13",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "14",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "15",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "16",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "17",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "18",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "19",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "20",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "21",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "22",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "23",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "24",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "25",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "26",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "27",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "28",
    color: "#0B76B7",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "29",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "30",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "31",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "32",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "33",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "34",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "35",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "36",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "37",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "38",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "39",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "40",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Manager",
  },
  {
    id: "41",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "42",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "43",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "44",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Manager",
  },
  {
    id: "45",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "46",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "47",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Manager",
  },
  {
    id: "48",
    color: "#0B76B7",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "49",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "50",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Manager",
  },
  {
    id: "51",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "52",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "53",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Manager",
  },
  {
    id: "54",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "55",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "56",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "57",
    color: "#0B76B7",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "58",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Manager",
  },
  {
    id: "59",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "60",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "29",
    Grade: "Grade B",
    title: "Manager",
  },
];
export const ListTable = [
  {
    id: "1",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "2",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "3",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "4",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "5",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "6",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "7",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "8",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "9",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
  {
    id: "10",
    No: "1",
    of_points: "Behavioral indicators",
    Index_title: "organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
  },
];
export const Notification = [
  {
    id: "1",
    title: "Job (Product Manager) Unemployed",
    color: "#FD8F02",
    title2: "Basic Info",
  },
  {
    id: "2",
    title: "Employed, (Ahmad Rezaei) above job grade",
    color: "#0A9AD7",
    title2: "Employees on This Job",
  },
  {
    id: "3",
    title: "Employed (Ahmad Rezaei) below job rank",
    color: "#F23030",
    title2: "Employees on This Job",
  },
];
export const Indicators = [
  {
    No: "1",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "2",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "3",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "4",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "5",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "6",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "7",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "8",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "9",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "10",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "11",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "12",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "13",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "14",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "15",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "16",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "17",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
];
export const GeneralMock = [
  {
    id:"1",
    Grade: "Grade A",
    gradeColor: "#22C55E",
    Grouping: "Behavioral indicators",
    ofpoint: "0",
    uptopoints: "60",
    Description: "High performance",
  },
  {
    id:"2",
    Grade: "Grade B",
    gradeColor: "#3B82F6",
    Grouping: "Technical indicators",
    ofpoint: "20",
    uptopoints: "80",
    Description: "Good performance",
  },
  {
    id:"3",
    Grade: "Grade A",
    gradeColor: "#F97316",
    Grouping: "Behavioral indicators",
    ofpoint: "0",
    uptopoints: "60",
    Description: "High performance",
  },
  {
    id:"4",
    Grade: "Grade B",
    gradeColor: "#EF4444",
    Grouping: "Technical indicators",
    ofpoint: "20",
    uptopoints: "80",
    Description: "Good performance",
  },{
    id:"5",
    Grade: "Grade A",
    gradeColor: "#22C55E",
    Grouping: "Behavioral indicators",
    ofpoint: "0",
    uptopoints: "60",
    Description: "High performance",
  },
  {
    id:"6",
    Grade: "Grade B",
    gradeColor: "#3B82F6",
    Grouping: "Technical indicators",
    ofpoint: "20",
    uptopoints: "80",
    Description: "Good performance",
  },
  {
    id:"7",
    Grade: "Grade A",
    gradeColor: "#F97316",
    Grouping: "Behavioral indicators",
    ofpoint: "0",
    uptopoints: "60",
    Description: "High performance",
  },
  {
    id:"8",
    Grade: "Grade B",
    gradeColor: "#EF4444",
    Grouping: "Technical indicators",
    ofpoint: "20",
    uptopoints: "80",
    Description: "Good performance",
  },
]
export const JDPageList = [
  {
    id:"1",
    Grade: "Grade A",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",
    score: "650"
  },
  {
    id:"2",
    Grade: "Grade B",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",

    score: "650"
  },
  {
    id:"3",
    Grade: "Grade c",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",

    score: "650"
  },
  {
    id:"4",
    Grade: "Grade B",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",

    score: "650"
  },{
    id:"5",
    Grade: "-",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"no",
    score: "650"
  },
  {
    id:"7",
    Grade: "Grade A",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",

    score: "650"
  },
  {
    id:"8",
    Grade: "-",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"no",

    score: "650"
  },
  {
    id:"9",
    Grade: "Grade A",
    gradeColor: "#22C55E",
    Job_title: "Financial expert",
    unit: "finance",
    grade_status:"has",

    score: "650"
  },{
    id: "10",
    Grade: "-",
    Job_title: "HR Manager",
    unit: "HR",
    grade_status: "no",
    score: "540"
  },
];
export const GRADE_OPTIONS = [
  { id: "Grade A", name: "Grade A" },
  { id: "Grade B", name: "Grade B" },
  { id: "Grade C", name: "Grade C" },
  { id: "Grade D", name: "Grade D" },
];

export const GROUP_OPTIONS = [
  { id: "Behavioral indicators", name: "Behavioral indicators" },
  { id: "Technical indicators", name: "Technical indicators" },
];

export const OF_POINTS = [
  { id: 0, name: "0" },
  { id: 20, name: "20" },
  { id: 40, name: "40" },
];

export const UP_TO_POINT = [
  { id: 60, name: "60" },
  { id: 80, name: "80" },
  { id: 100, name: "100" },
];

// ✅ مطابق تایپ ColorItem (value/label)
export const GRADE_COLORS = [
  { value: "#22C55E", label: "Green" },
  { value: "#3B82F6", label: "Blue" },
  { value: "#F97316", label: "Orange" },
  { value: "#EF4444", label: "Red" },
];

export const ProfileEmployee = [
  {
    id: "1",
    image:
      "https://images.stockcake.com/public/8/7/c/87cc3b74-63de-41ab-9955-334e9488c1e0_large/handsome-model-posing-stockcake.jpg",
    Name: "jahan hatami",
    category: "Mentor",
    icon: Verify,
    info: true,
  },
  {
    id: "2",
    image:
      "https://thumbs.dreamstime.com/b/portrait-most-handsome-man-entire-world-80648074.jpg",
    Name: "ali maleki",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "3",
    image:
      "https://png.pngtree.com/png-vector/20240528/ourmid/pngtree-front-view-of-a-smiling-business-woman-png-image_12509704.png",
    Name: "sara asadi",
    category: "Front-end",
    icon: Verify,
    info: true,
  },
  {
    id: "4",
    image:
      "https://burst.shopifycdn.com/photos/model-in-gold-fashion.jpg?width=1000&format=pjpg&exif=0&iptc=0",
    Name: "mahsa omidi",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "5",
    image:
      "https://preview.redd.it/kimiya-hoseini-irtr-v0-cfpm6w0gt1pb1.jpg?width=640&crop=smart&auto=webp&s=8f52a724cf8fba99e64f5b0ae5778cab327c038a",
    Name: "asal hatami",
    category: "Designer",
    icon: Verify,
    info: true,
  },
  {
    id: "6",
    image:
      "https://i.pinimg.com/236x/3d/74/f3/3d74f3bf49034c74b7dd2f804ca9458d.jpg",
    Name: "Hosein fahmideh",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "7",
    image:
      "https://img.freepik.com/free-photo/young-woman-blue-sweater-autumn-park_1303-11368.jpg?semt=ais_hybrid&w=740&q=80",
    Name: "Nasim Moradi",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "8",
    image:
      "https://img.freepik.com/free-photo/smiling-beautiful-young-woman-standing-posing_171337-11412.jpg?semt=ais_hybrid&w=740&q=80",
    Name: "Maryam Mohammadi ",
    category: "Ceo",
    icon: Verify,
    info: false,
  },
  {
    id: "9",
    image:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?cs=srgb&dl=pexels-italo-melo-881954-2379004.jpg&fm=jpg",
    Name: "Mohsen Mosalman ",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "10",
    image:
      "https://i.pinimg.com/236x/c2/88/0a/c2880a8f427b543079d893068ccae83f.jpg",
    Name: "Bradd Pitt ",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "11",
    image:
      "https://preview.redd.it/kimiya-hoseini-irtr-v0-cfpm6w0gt1pb1.jpg?width=640&crop=smart&auto=webp&s=8f52a724cf8fba99e64f5b0ae5778cab327c038a",
    Name: "asal hatami",
    category: "Designer",
    icon: Verify,
    info: true,
  },
  {
    id: "12",
    image:
      "https://i.pinimg.com/236x/3d/74/f3/3d74f3bf49034c74b7dd2f804ca9458d.jpg",
    Name: "Hosein fahmideh",
    category: "back-end",
    icon: Verify,
    info: false,
  },
  {
    id: "13",
    image:
      "https://thumbs.dreamstime.com/b/portrait-most-handsome-man-entire-world-80648074.jpg",
    Name: "ali maleki",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "14",
    image:
      "https://png.pngtree.com/png-vector/20240528/ourmid/pngtree-front-view-of-a-smiling-business-woman-png-image_12509704.png",
    Name: "sara asadi",
    category: "Front-end",
    icon: Verify,
    info: true,
  },
  {
    id: "15",
    image:
      "https://images.stockcake.com/public/8/7/c/87cc3b74-63de-41ab-9955-334e9488c1e0_large/handsome-model-posing-stockcake.jpg",
    Name: "jahan hatami",
    category: "Mentor",
    icon: Verify,
    info: false,
  },
  {
    id: "16",
    image:
      "https://thumbs.dreamstime.com/b/portrait-most-handsome-man-entire-world-80648074.jpg",
    Name: "ali maleki",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "17",
    image:
      "https://png.pngtree.com/png-vector/20240528/ourmid/pngtree-front-view-of-a-smiling-business-woman-png-image_12509704.png",
    Name: "sara asadi",
    category: "Front-end",
    icon: Verify,
    info: true,
  },
  {
    id: "18",
    image:
      "https://burst.shopifycdn.com/photos/model-in-gold-fashion.jpg?width=1000&format=pjpg&exif=0&iptc=0",
    Name: "mahsa omidi",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "19",
    image:
      "https://preview.redd.it/kimiya-hoseini-irtr-v0-cfpm6w0gt1pb1.jpg?width=640&crop=smart&auto=webp&s=8f52a724cf8fba99e64f5b0ae5778cab327c038a",
    Name: "asal hatami",
    category: "Designer",
    icon: Verify,
    info: false,
  },
  {
    id: "20",
    image:
      "https://i.pinimg.com/236x/3d/74/f3/3d74f3bf49034c74b7dd2f804ca9458d.jpg",
    Name: "Hosein fahmideh",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "21",
    image:
      "https://m.media-amazon.com/images/M/MV5BMTQzMTI2NDQ5NV5BMl5BanBnXkFtZTgwMjM3Mjc1MjE@._V1_.jpg",
    Name: "Peyman maadi",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "22",
    image:
      "https://i.pinimg.com/originals/6a/94/03/6a9403a53cbe94f633dc0446baa0ea4e.jpg",
    Name: "mahak ashouri",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "23",
    image:
      "https://static.vecteezy.com/system/resources/previews/036/297/773/non_2x/ai-generated-business-woman-showing-thumbs-up-on-a-transparent-background-free-png.png",
    Name: "sara morsali",
    category: "back-end",
    icon: Verify,
    info: true,
  },
  {
    id: "24",
    image:
      "https://cdn.pinno.app/api/internal/cdb/contents/saqarnorouzi@instagram_photo_HIGH/0/238519",
    Name: "Saqar norouzi",
    category: "Front-end",
    icon: Verify,
    info: true,
  },
  {
    id: "25",
    image:
      "https://burst.shopifycdn.com/photos/model-in-gold-fashion.jpg?width=1000&format=pjpg&exif=0&iptc=0",
    Name: "mahsa omidi",
    category: "back-end",
    icon: Verify,
    info: false,
  },
  {
    id: "26",
    image:
      "https://preview.redd.it/kimiya-hoseini-irtr-v0-cfpm6w0gt1pb1.jpg?width=640&crop=smart&auto=webp&s=8f52a724cf8fba99e64f5b0ae5778cab327c038a",
    Name: "asal hatami",
    category: "Designer",
    icon: Verify,
    info: true,
  },
  {
    id: "27",
    image:
      "https://png.pngtree.com/png-vector/20240528/ourmid/pngtree-front-view-of-a-smiling-business-woman-png-image_12509704.png",
    Name: "sara asadi",
    category: "Front-end",
    icon: Verify,
    info: true,
  },
  {
    id: "28",
    image:
      "https://images.stockcake.com/public/8/7/c/87cc3b74-63de-41ab-9955-334e9488c1e0_large/handsome-model-posing-stockcake.jpg",
    Name: "jahan hatami",
    category: "Mentor",
    icon: Verify,
    info: true,
  },
  {
    id: "29",
    image:
      "https://thumbs.dreamstime.com/b/portrait-most-handsome-man-entire-world-80648074.jpg",
    Name: "ali maleki",
    category: "Ceo",
    icon: Verify,
    info: true,
  },
  {
    id: "30",
    image:
      "https://png.pngtree.com/png-vector/20240528/ourmid/pngtree-front-view-of-a-smiling-business-woman-png-image_12509704.png",
    Name: "sara asadi",
    category: "Front-end",
    icon: Verify,
    info: false,
  },
  {
    id: "31",
    image:
      "https://burst.shopifycdn.com/photos/model-in-gold-fashion.jpg?width=1000&format=pjpg&exif=0&iptc=0",
    Name: "mahsa omidi",
    category: "back-end",
    icon: Verify,
    info: true,
  },
];
export const CostEmployee = [
  {
    index:
      "Highly Contextualized Domain-Specific Expert-Level Theoretical and Practical Knowledge",
    Points_Required: "Grade 5",
    Person: <span className="text-danger">"Grade 2"</span>,
    color: "#8A1B1B",
  },
  {
    index: "Decision Making",
    Points_Required: "Grade 4",
    Person: "Grade 4",
    color: "#136234",
  },
  {
    index: "Leadership Experience",
    Points_Required: "Grade 2",
    Person: "Grade 5",
    color: "#05587A",
  },
];
