import { number } from "framer-motion";
import { CloseCircle, Global, Location, TickCircle } from "iconsax-reactjs";

export const EntryExitData = [
  {
    Id: 1,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 2,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Location /> <span>Location</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 3,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 4,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Location /> <span>Location</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
  {
    Id: 5,
    Date: "2025/01/01",
    Time: "09:00",
    Type: "Clock out",
    Type2: (
      <div className="flex items-center justify-center text-center gap-1">
        <Global /> <span>Ip</span>
      </div>
    ),
    Ip: "127.0.0.1",
  },
];
export const PersonalList = [
  {
    Date: "2025/01/01 Wednesday (Absence)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    isHoliday: false,
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    isHoliday: true,
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Absence)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: false,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: false,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
  {
    Date: "2025/01/01 Wednesday (Present)",
    Shift: "12345",
    "Check in": "09:00",
    "Check out": "09:00",
    Presence: "09:00",
    Overdue: "09:00",
    Delay: "09:00",
    isHoliday: true,
    "Haste to leave": "09:00",
    Request: "Permision from 13:00 to 18:00",
  },
];
export const ReportPersonnal = [
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
  {
    تاریخ: "شنبه 11/2/1404",
    شیفت: "اداری 1",
    ورود: "09:00",
    خروج: "09:00",
    حضور: "09:00",
    "اضافه کار": "09:00",
    تاخیر: "02:00",
    تعجیل: "02:00",
    درخواست: "",
  },
];
export const ListApprovals = [
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: <TickCircle color="green" variant="Bold" />,
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="red" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
  {
    No: 1,
    "Request Type": "Hourly Leave",
    Issuer: "Zahra Pakniyat",
    Duration: "3 Hours",
    "From Date": "2025/01/20",
    "Request Number": "1223425",
    status: (
      <span>
        <TickCircle color="green" variant="Bold" />
      </span>
    ),
  },
];
export const Allocatio = [
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
  {
    numer: 1,
    ChooseShift: "Administrative",
    FromDate: "Employee",
    organization: "Zahra Pakniyat",
    Department: "2025/01/10",
    Employee: "2025/01/10",
    JobTitle: "momom",
    type: "Person",
  },
];
export const organization = [
  { id: "1", title: "Number of jobs graded", number: "28" },
  { id: "2", title: "Number of employees with grades", number: "53" },
  { id: "3", title: "Ungraded jobs", number: "12" },
  { id: "4", title: "Unemployed jobs", number: "3" },
];
export const JD = [
  {
    id: "1",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "2",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "3",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Administrative Assistant",
  },
  {
    id: "4",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "5",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "6",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "7",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "8",
    color: "#FFCC00",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
  {
    id: "9",
    color: "#FD1B51",
    title2: "Number of employees:",
    title3: "Status",
    number: "2",
    Grade: "Grade B",
    title: "Administrative Assistant",
  },
  {
    id: "10",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Developer",
  },
  {
    id: "11",
    color: "",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "-",
    title: "Designer",
  },
  {
    id: "11",
    color: "#A212D2",
    title2: "Number of employees:",
    title3: "Status",
    number: "1595",
    Grade: "Grade B",
    title: "Designer",
  },
];
export const ListTable=[
    {
    id: "1",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "2",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "3",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "4",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "5",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "6",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "7",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "8",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "9",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
},{
    id: "10",
    No:"1",
    of_points:"Behavioral indicators",
    Index_title:"organizational impact",
    Grade: "Grade B",
    Creation_date: "2022/19/10",
}
]
export const Notification = [
  {
    id: "1",
    title: "Job (Product Manager) Unemployed",
    color: "#FD8F02",
    title2: "Basic Info",
  },
  {
    id: "2",
    title: "Employed, (Ahmad Rezaei) above job grade",
    color: "#0A9AD7",
    title2: "Employees on This Job",
  },
  {
    id: "3",
    title: "Employed (Ahmad Rezaei) below job rank",
    color: "#F23030",
    title2: "Employees on This Job",
  },
];
export const Indicators = [
  {
    No: "1",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "2",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "3",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "4",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "5",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "6",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "7",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "8",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "9",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "10",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "11",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "12",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "13",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "14",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "15",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "16",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
  {
    No: "17",
    Grouping: "Behavioral indicators",
    Index_title: "organizational impact",
    type: "Numerical",
    weight: "20%",
    Creation_data: "2022/19/10",
  },
];
