export * from './JobOffersIcon';
export * from './TelegramIcon';
export * from './LinkedinIcon';
export * from './InstagramIcon';
export * from './WhatsAppIcon';
export * from './CupStarIcon';
export * from './AcademyIcon';
export * from './JobOpportunitiesIcon';
export * from './BuildingIcon';
export * from './SoftSkillsIcon'
