export * from '@module/hrlink/icons/JobOffersIcon';
export * from '@module/hrlink/icons/TelegramIcon';
export * from '@module/hrlink/icons/LinkedinIcon';
export * from '@module/hrlink/icons/InstagramIcon';
export * from '@module/hrlink/icons/WhatsAppIcon';
export * from '@module/hrlink/icons/CupStarIcon';
export * from '@module/hrlink/icons/AcademyIcon';
export * from '@module/hrlink/icons/JobOpportunitiesIcon';
export * from '@module/hrlink/icons/BuildingIcon';
export * from '@module/hrlink/icons/SoftSkillsIcon'
