export const faCommon = {
  login: 'ورود',
  companyName: 'نام شرکت',
  first_name: 'نام',
  last_name: 'نام خانوادگی',
  national_code: 'کد ملی',
  date_of_birth: 'تاریخ تولد',
  gender: 'جنسیت',
  marital_status: 'وضعیت تاهل',
  military_service_status: 'وضعیت نظام وظیفه',
  city: 'شهر',
  address: 'آدرس',
  minimum_salary: 'حداقل حقوق',
  working_category: 'رسته کاری',
  organizational_category: 'دسته سازمانی',
  social_media_links: 'لینک های رسانه های اجتماعی',
  descriptions: 'توضیحات',
  save_changes: 'ذخیره تغییرات',
  ed_tour: 'تور آموزشی',
  upgrade: 'ارتقا دهید',
  generalSetting: 'تنظیمات کلی',
  persian: 'فارسی',
  english: 'انگلیسی',
  logout: 'خروج از حساب',
  dashboard: 'داشبورد',
  workspace: 'میزکار',
  performance: 'مدیریت عملکرد',
  recruitment: 'مدیریت استخدام',
  payroll: 'حقوق و دستمزد',
  attendance: 'حضور و غیاب',
  projectManager: 'مدیریت پروژه',
  facilities: 'امکانات',
  basicInfo: 'اطلاعات پایه',
  judgmentIssued: 'صدور حکم',
  salaryCalculation: 'محاسبه حقوق',
  payrollSlip: 'فیش‌حقوقی',
  reporting: 'گزارشات',
  settings: 'تنظیمات',
  individualOrder: 'حکم فردی',
  groupOrder: 'حکم گروهی',
  search: 'جستجو',
  addNewOne: 'افزودن',
  title: 'عنوان',
  describeTitle: 'توضیح عنوان',
  organizations: 'سازمان‌ها',
  departmentsUnits: 'بخش‌ها/واحدها',
  person: 'فرد',
  personPeople: 'فرد/افراد',
  name: 'نام',
  describeName: 'توضیح نام',
  types: 'انواع',
  describeTypes: 'توضیح انواع',
  effectiveDate: 'تاریخ مؤثر',
  pickADate: 'انتخاب تاریخ',
  Insurance: 'بیمه',
  describeInsurance: 'توضیح بیمه',
  taxBranch: 'شعبه مالیاتی',
  describeTax: 'توضیح مالیات',
  category: 'دسته‌بندی',
  describeCategory: 'توضیح دسته‌بندی',
  changing: 'در حال تغییر',
  notChanging: 'بدون تغییر',
  cancel: 'انصراف',
  submit: 'ثبت',
  no: 'ردیف',
  list: 'لیست',
  primeNumber: 'عدد اول',
  eleman: 'عنصر',
  coefficient: 'ضریب',
  fixedNumber: 'عدد ثابت',
  calculationInEid: 'محاسبه در عید',
  years: 'سال‌ها',
  actions: 'اقدامات',
  total: 'جمع',
  workersShareInsurance: 'بیمه سهم کارگر',
  employersShareInsurance: 'بیمه سهم کارفرما',
  unemploymentInsurance: 'بیمه بیکاری',
  noEditTax: 'عدم ویرایش مالیات',
  editTax: 'ویرایش مالیات',
  addNewIndividualOrder: 'افزودن حکم فردی جدید',
  addNewGroupOrder: 'افزودن حکم گروهی جدید',
  filter: 'فیلتر',
  describeText: 'توضیح متن',
  time: 'زمان',
  date: 'تاریخ',
  general_details: 'جزئیات کلی',
  amount: 'مقدار',
  salaryCalculations: 'محاسبات حقوق',
  organization: 'سازمان‌ها',
  calculate: 'حساب کردن',
  revert: 'بازگرداندن',
  status: 'وضعیت',
  nuPeople: 'تعداد اشخاص',
  nuEdit: 'تعداد ویرایش‌ها',
  totalAmount: 'مبلغ کل',
  people: 'نفر',
  times: 'بار',
  user_name: 'نام کاربری',
  user_password: 'رمز عبور',
  remember_me: 'مرا یه خاطر بسپار',
  forgot_password: 'رمز عبور را فراموش کرده اید؟',
  sign_in: 'ورود',
  sign_up: 'ثبت نام',
  or: 'یا',
  sign_in_with_username: 'ورود با نام کاربری',
  sign_in_with_phone_number: 'ورود با شماره تلفن',
  sign_in_with_google: 'ورود با گوگل',
  username_is_required: 'نام کاربری الزامی است',
  otp_is_required: 'وارد کردن کد تأیید (OTP) الزامی است.',
  otp_must_be_six_digits: 'کد تأیید (OTP) باید ۶ رقم باشد.',
  organization_name: 'نام سازمان',
  full_name: 'نام و نام خانوادگی',
  email: 'ایمیل',
  password: 'رمز عبور',
  phone: 'شماره تماس',
  password_confirmation: 'تکرار رمز عبور',
  enter_your_phone: 'موبایل را وارد کنید ...',
  enter_your_email: 'ایمیل را وارد کنید ...',
  enter_your_password: 'رمز عبور را وارد کنید ...',
  enter_your_confirm_password: 'تکرار رمز عبور را وارد کنید ...',
  enter_your_national_id_code: 'نام سازمان خود را وارد کنید...',
  enter_your_national_code: 'کد ملی خود را وارد کنید ...',
  enter_your_first_name: 'نام را وارد کنید ...',
  enter_your_last_name: 'نام خانوادگی را وارد کنید ...',
  enter_otp_code: 'کد تأیید (OTP) را وارد کنید.',
  password_is_required: 'رمر عبور را الزانی است',
  sign_up_now: 'همین حالا ثبت نام کنید',
  have_an_account: 'حساب کاربری دارید؟',
  dont_have_an_account: 'حساب کاربری ندارید؟',
  please_enter_your_information: 'لطفا اطلاعات خود را وارد کنید!',
  welcome_back: 'خوش آمدید!',
  please_sign_in_to_our_hrbox_account: 'لطفاً به حساب "HRBox" خود وارد شوید.',
  please_sign_in_to_our_hrlink_account: 'لطفاً به حساب "HRLink" خود وارد شوید.',
  pick_your_country: 'کشور خود را انتخاب کنید',
  please_enter_the_code_sent_your_phone_number:
    'لطفاً کد ارسال شده به شماره تلفن خود را وارد کنید',
  login_with_phone_number: 'ورود با شماره تلفن!',
  send_code: 'ارسال کد',
  transferring_to_user_panel: 'انتقال به پنل کاربری',
  to_resend: 'ارسال مجدد',
  new_user_pass: 'رمز عبور جدید',
  confirm_user_pass: 'تکرار رمز عبور جدید',
  enter_new_password: 'رمز عبور جدید را وارد کنید!',
  forget_password: 'فراموشی رمز عبور!',
  phone_number_is_required: 'شماره تماس الزامی است',
  phone_number_must_contain_only_digits: 'شماره تلفن باید فقط شامل رقم باشد',
  employers_registration: 'ثبت نام کارفرمایان',
  job_seekers_registration: 'ثبت نام کارجویان',
  resend_code: 'ارسال مجدد',
  otp_is_correct_redirecting:
    'کد یکبار مصرف صحیح است. در حال هدایت به پنل کاربری...',
  lorem:
    'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است',
};
